TextGallery.Client/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TextGallery.Client.Controllers
{
    public class AuthorizationController : Controller
    {
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

TextGallery.Client/Controllers/TextController.cs
using IdentityModel.Client;
using ImageGallery.Model;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace TextGallery.Client
{
    [Authorize]
    public class TextController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public TextController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory ??
                throw new ArgumentNullException(nameof(httpClientFactory));
        }
        public async Task<IActionResult> Index()
        {
            await WriteOutIdentiotyInformation();

            return View();
        }

        public async Task<IActionResult> Index1()
        {
            var httpClient = _httpClientFactory.CreateClient("APIClient");

            var request = new HttpRequestMessage(
                HttpMethod.Get,
                "/api/images/");

            var response = await httpClient.SendAsync(
                request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();

            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                return View(new GalleryIndexViewModel(
                    await JsonSerializer.DeserializeAsync<List<Image>>(responseStream)));
            }

        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> OrderAddress()
        {
            var idpClient = _httpClientFactory.CreateClient("IDPAPI");

            var metadataResponse = await idpClient.GetDiscoveryDocumentAsync();

            if (metadataResponse.IsError)
                throw new Exception("metadataResponse: ", metadataResponse.Exception);

            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

            var userinfoResponse = await idpClient.GetUserInfoAsync(
                    new UserInfoRequest
                    {
                        Address = metadataResponse.UserInfoEndpoint,
                        Token = accessToken
                    }
                );

            if (userinfoResponse.IsError)
                throw new Exception("userinfoResponse: ", userinfoResponse.Exception);

            var address = userinfoResponse.Claims.FirstOrDefault(a => a.Type == "address")?.Value;


            return View(new OrderAddressViewModel(address));
        }

        public async Task<IActionResult> EditImage(Guid id)
        {

            var httpClient = _httpClientFactory.CreateClient("APIClient");

            var request = new HttpRequestMessage(
                HttpMethod.Get,
                $"/api/images/{id}");

            var response = await httpClient.SendAsync(
                request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();

            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                var deserializedImage = await JsonSerializer.DeserializeAsync<Image>(responseStream);

                var editImageViewModel = new EditImageViewModel()
                {
                    Id = deserializedImage.Id,
                    Title = deserializedImage.Title
                };

                return View(editImageViewModel);
            }
        }

        public async Task Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);

            var idpClient = _httpClientFactory.CreateClient("IDPAPI");

            var metadataResponse = await idpClient.GetDiscoveryDocumentAsync();

            if (metadataResponse.IsError)
                throw new Exception("metadataResponse: ", metadataResponse.Exception);


            var tokenRevocationResponse = await idpClient.RevokeTokenAsync(
                    new TokenRevocationRequest
                    {
                        Address = metadataResponse.RevocationEndpoint,
                        ClientId = "textgalleryclient",
                        ClientSecret = "secret2",
                        Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken)
                    }
                );
            if (tokenRevocationResponse.IsError)
            {
                throw new Exception(tokenRevocationResponse.Error);
            }

            var refreshTokenRevocationResponse = await idpClient.RevokeTokenAsync(
                    new TokenRevocationRequest
                    {
                        Address = metadataResponse.RevocationEndpoint,
                        ClientId = "textgalleryclient",
                        ClientSecret = "secret2",
                        Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.RefreshToken)
                    }
                );
            if (refreshTokenRevocationResponse.IsError)
            {
                throw new Exception(refreshTokenRevocationResponse.Error);
            }
        }

        public async Task WriteOutIdentiotyInformation()
        {
            //get the saved entity
            var identityToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken);

            //write it out
            Debug.WriteLine($"Identity token: {identityToken}");

            //write out the user claims
            foreach (var claim in User.Claims)
            {
                Debug.WriteLine($"Claim type: {claim.Type} - Claim value: {claim.Value}");

            }
        }
    }
}

TextGallery.Client/Views/Authorization/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}

<h1>AccessDenied</h1>

TextGallery.Client/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Text Gallery</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Image Gallery</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Text" asp-action="Index">Home</a></li>
                    @if (User.IsInRole("admin"))
                    {
                        <li><a asp-area="" asp-controller="Text" asp-action="Index">Role Admin</a></li>
                    }
                    @{
                        var res = await AuthorizationService.AuthorizeAsync(User, "CanOrderFrame");
                    }
                    @if (res.Succeeded)
                    {
                        <li><a asp-area="" asp-controller="Text" asp-action="Index">Policy CanOrderFrame</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Text" asp-action="Logout">Logout</a></li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Text Gallery</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

TextGallery.Client/Views/Text/EditImage.cshtml
@model TextGallery.Client.EditImageViewModel

@{
    ViewData["Title"] = "EditImage";
}

<h1>EditImage</h1>


<h2 class="leftMarginSmaller">Edit Image Title</h2>

<form asp-action="EditImage" method="post" class="form-horizontal" role="form">

    <div class="form-horizontal leftMarginDefault">

        <div class="form-group">
            <div>You image's title</div>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <div>
                <input type="submit" class="btn btn-primary" value="Change title" />
            </div>
        </div>
    </div>
</form>

TextGallery.Client/Views/Text/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div>
    Authorize Text
</div>
@if (User.IsInRole("admin"))
{
    <h2><a asp-area="" asp-controller="Text" asp-action="OrderAddress">Admin OrderAddress</a></h2>
}

    <h2><a asp-area="" asp-controller="Text" asp-action="OrderAddress">OrderAddress</a></h2>


@if (User.Identity.IsAuthenticated)
{
    <h2><a asp-area="" asp-controller="Text" asp-action="Logout">Logout</a></h2>
}

TextGallery.Client/Views/Text/Index1.cshtml
@model TextGallery.Client.GalleryIndexViewModel

<div class="bottomMarginDefault">
</div>

<div class="container">
    @foreach (var item in Model.Images)
    {
        <div class="pull-left col-md-4">
            <div>
                <img class="thumbnailImage" src="@("https://localhost:44366/images/" + item.FileName)" />
            </div>
            <div>
                <div class="h5">@item.Title</div>
                <div class="bottomMarginDefault">
                    <a asp-action="EditImage" asp-controller="Text" asp-route-id="@item.Id">Edit title</a> |
                    <a asp-action="DeleteImage" asp-controller="Text" asp-route-id="@item.Id">Delete image</a>
                </div>
            </div>
        </div>
    }
</div> 

TextGallery.Client/Views/Text/OrderAddress.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model TextGallery.Client.OrderAddressViewModel

@{
    ViewData["Title"] = "OrderAddress";
}

<h1>OrderAddress</h1>

<div>@Model.Address</div>